version: 2

project_name: probedesk

env:
  - CGO_ENABLED=0

builds:
  - id: probedesk
    main: ./main.go
    goos:
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
    binary: probedesk.exe

archives:
  - id: windows
    builds: [probedesk]
    format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

release:
  github:
    owner: RainyRoot
    name: ProbeDesk
