version: 2

project_name: probedesk

env:
  - CGO_ENABLED=0

builds:
  - main: ./main.go
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w

archives:
  - id: windows
    builds:
      - windows-amd64
      - windows-arm64
    format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

  - id: unix
    builds:
      - linux-amd64
      - linux-arm64
      - darwin-amd64
      - darwin-arm64
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

release:
  github:
    owner: RainyRoot
    name: ProbeDesk
