# .goreleaser.yml for ProbeDesk (v2 schema)
version: 2

project_name: probedesk

env:
  - CGO_ENABLED=0

builds:
  - main: ./main.go
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w

archives:
  - format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

release:
  github:
    owner: RainyRoot
    name: ProbeDesk